# ----------------------------------------------------------------------------------------------------
# Template to deploy a pre-built Azure Website artifact to one environment
# ----------------------------------------------------------------------------------------------------
parameters: 
- name: variableGroupName
  default:  'myVariableGroup'
- name: environmentName
  default:  'DEV'
- name: zipFileName
  default: 'App.zip'

# ------------------------------------------------------------------------------------------------------------------------
jobs:
- deployment: Deploy${{ parameters.environmentName }}Website
  displayName: Initialize ${{ parameters.environmentName }} Deploy Website
  environment: ${{ parameters.environmentName }}

- job: DeployApplication${{ parameters.environmentName }}Website
  displayName: Deploy ${{ parameters.environmentName }} Website
  variables:
    - group: ${{ parameters.variableGroupName }}
    - name: environmentNameLower
      value: ${{ lower(parameters.environmentName) }}
    - name: zipFileName
      value: '${{ parameters.zipFileName }}'

  steps:
  - task: DownloadPipelineArtifact@2
    displayName: 'Download Artifacts'
    inputs:
      artifact: drop

  - bash: |
      backendServiceNameEnv=$(echo "$(backendServiceNamePrefix)-$(environmentNameLower)" | tr '[:upper:]' '[:lower:]')
      echo "backendServiceNameEnv=$backendServiceNameEnv"
      echo "##vso[task.setvariable variable=backendServiceNameEnv]$backendServiceNameEnv"
    displayName: 'Create Variables'

  - task: CmdLine@2
    inputs:
      script: |
        echo "subscriptionId=$(subscriptionId)"
        echo "subscriptionName=$(subscriptionName)"
        echo "resourceGroupName=$(resourceGroupName)"
        echo "environmentNameLower=$(environmentNameLower)"
        echo "backendServiceNamePrefix=$(backendServiceNamePrefix)"
        echo "backendServiceNameEnv=$(backendServiceNameEnv)"
        echo "zipFileName=$(zipFileName)"
        echo "Set Subscription Command:"
        echo "  az account set --subscription $(subscriptionId)"
        echo "Deploy Command:"
        echo "  az webapp deployment source config-zip -g $(resourceGroupName) -n $(backendServiceNameEnv) --src $(Pipeline.Workspace)/$(zipFileName)"
        echo "Pipeline workspace: $(Pipeline.Workspace)"
        echo "DefaultWorkingDirectory: $(System.DefaultWorkingDirectory)"
        echo "Directory of pipeline workspace:"
        tree $(Pipeline.Workspace)
    displayName: 'Display Variables and Tree'
    continueOnError: true

  - task: AzureCLI@2
    displayName: 'Deploy Web App'
    inputs:
      azureSubscription: $(subscriptionName)
      resourceGroupName: $(resourceGroupName)
      scriptType: bash
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      inlineScript: |
        az account set --subscription $(subscriptionId)
        az webapp deployment source config-zip -g $(resourceGroupName) -n $(backendServiceNameEnv) --src $(Pipeline.Workspace)/$(zipFileName)
