# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to update the search index only
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEMO']
- name: variableGroupName
  default: 'myVariableGroupName'
- name: dataFolder
  default: 'data'
- name: dataFiles
  default: '*'

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ each environmentName in parameters.environments }} :
  - stage: Update${{ environmentName }}Search
    displayName: Update ${{ environmentName }} Search
    jobs:
    - template: templates/update-search-template.yml
      parameters:
        variableGroupName: ${{ parameters.variableGroupName }}
        environmentName: ${{ environmentName }}
        dataFolder: ${{ parameters.dataFolder }}
        dataFiles: ${{ parameters.dataFiles }}
