name: Frontend linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install frontend dependencies
              run: |
                cd ./app/frontend
                npm install
            - name: Run Prettier
              run: npx prettier --check .
